quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/tanvoid0?currentSchema=tanquark
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      default-schema: tanquark
      #      generation: drop-and-create
      generation: update
      # values
      #   drop-and-create -> Drop Schema and Recreate
      #   update -> update existing database
  log:
    sql: true
    level: DEBUG

  modelmapper:
    enabled: true

  native:
    resources:
      includes: publicKey.pem
  #  smallrye-jwt:
  #    enabled: true
  #    token:
  #      issuer: my-issuer
  #      subject: my-subject
  smallrye-openapi:
    path: /swagger

mp:
  jwt:
    timeout: 7
    verify:
      publickey:
        location: publicKey.pem
        # Default: RS256
      #        algorithm: ES256
      issuer: https://example.com/issuer
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
#    encrypt:
#      key:
#        location: jwt/publicKey.pem